### ISSUE TITLE
parallel scan

### ISSUE THREAD

**Issue by Howuhh** [radarFudan/mamba-minimal-jax#1]
Hi! Just a quick question. Isn't it possible to use a parallel scan already existing in jax? https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.associative_scan.html (with binary operator from S5)

I used it in the S5, LRU, LinearRNN implementations before and it was quite fast. The Mamba doesn't seem to be much different from these models, as far as I can tell from self.ssm.

**Comment by radarFudan** [comment]
Yes, I tried to use associative_scan to speedup the forward. It's in the speedup branch. However, I'm not sure whether JAX could handle the backward properly.

**Comment by Howuhh** [comment]
I see speed up from 52 to 9 mins there (in the `speedup_log.md`)! Don't think that this is just 'slight'... For inference speedup, generation should be rewritten in the RNN mode tho. See https://github.com/lindermanlab/S5/issues/4

**Comment by radarFudan** [comment]
Yes, you are right! The inference using hidden state is part of TODOs. 

Also, naive trial with backward propagation using the JAX associative scan is feasible but there seems to be some additional memory cost (not 100% sure, checking in progress). I'll compare different parallel scans for mamba.
1. What's the most memory saving parallel scan method.
2. What's the fastest parallel scan method.
